// <auto-generated />
namespace Csystems.Aula02.Persistencia.Dados.SQLServer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RevisaoCampoCliente : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RevisaoCampoCliente));
        
        string IMigrationMetadata.Id
        {
            get { return "201609031803538_RevisaoCampoCliente"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
